import 'package:flutter/material.dart';

final appTheme = ThemeData(
  appBarTheme: AppBarTheme(
    centerTitle: true,
    toolbarHeight: kToolbarHeight + 16,
    scrolledUnderElevation: 1,
    elevation: 1,
    shadowColor: _darkColorScheme.secondary,
  ),
  bottomNavigationBarTheme: BottomNavigationBarThemeData(
    backgroundColor: _darkColorScheme.surface,
    selectedItemColor: _darkColorScheme.primary,
    unselectedItemColor: _darkColorScheme.onSurfaceVariant,
    type: BottomNavigationBarType.fixed,
    showUnselectedLabels: true,
  ),
  colorScheme: _darkColorScheme,
  bannerTheme: MaterialBannerThemeData(
    backgroundColor: _darkColorScheme.primaryContainer,
  ),
  useMaterial3: true,
  fontFamily: 'Poppins',
);

const _darkColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF005AC1),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD8E2FF),
  onPrimaryContainer: Color(0xFF001A41),
  secondary: Color(0xFF575E71),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFDBE2F9),
  onSecondaryContainer: Color(0xFF141B2C),
  tertiary: Color(0xFF715573),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFBD7FC),
  onTertiaryContainer: Color(0xFF29132D),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  outline: Color(0xFF74777F),
  onInverseSurface: Color(0xFFF2F0F4),
  inverseSurface: Color(0xFF303033),
  inversePrimary: Color(0xFFADC6FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF005AC1),
  outlineVariant: Color(0xFFC4C6D0),
  scrim: Color(0xFF000000),
  surface: Color(0xFFFAF9FD),
  onSurface: Color(0xFF1B1B1F),
  onSurfaceVariant: Color(0xFF44474F),
);
